### ISSUE TITLE
Missing addRemnants function

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [kirazy/vanilla-loaders-hd#2]
```
Failed to load mods: __vanilla-loaders-hd__/prototypes/functions.lua:46: attempt to call field 'createRemnants' (a nil value)
stack traceback:
	__vanilla-loaders-hd__/prototypes/functions.lua:46: in function 'addLoader'
	__RandomFactorioThings__/data-final-fixes.lua:54: in main chunk

Mods to be disabled:
• RandomFactorioThings (1.1.1)
```
[RandomFactorioThings source](https://github.com/JohnTheCoolingFan/RandomFactorioThings/tree/dev)

**Comment by kirazy** [comment]
Woops. Gimme a moment.

**Comment by kirazy** [comment]
Your current build of your mod doesn't load for me, I've pushed what I think will fix your issue, can you clone/download the current build and see if it works for you?

**Comment by JohnTheCoolingFan** [comment]
Yeah, it works now. Thanks!

**Comment by kirazy** [comment]
Commit 8466a7edca47bb3645cffae1625b6cf9424b6bb7 closes #2.

**Comment by CaveJohnson376** [comment]
Only two issues on this mod? Woah

**Comment by kirazy** [comment]
I only relatively recently published this on github; most people have been reporting bugs on the mod portal.
