### ISSUE TITLE
[Localization] mod-setting-description:vanillaLoaders-reskinLoaderReduxOnly contains semicolon, messing up Crowdin

### ISSUE THREAD

**Issue by adoa** [kirazy/vanilla-loaders-hd#5]
Similar to the case in Artisanal reskins, the semicolon is messing up the presentation of the string on Crowdin.
Please check:
https://crowdin.com/translate/factorio-mods-localization/702/en-de#31020

**Comment by kirazy** [comment]
I do love my semicolons. 

Commit b5eccec fixes this.
