### ISSUE TITLE
[Bug] No loaders with v.1.1.0

### ISSUE THREAD

**Issue by GermanKermanFactorio** [kirazy/vanilla-loaders-hd#6]
Fresh install of Factorio 1.1.0 (linux 64). Downloaded Vanilla Loaders 1.1.0 from within the game. Restarted the game and there are no loaders. No item and no technology to unlock them.

Moved over the old 0.18.9 version and changed factorio version to 1.1 in info.json. Loaders show up and seem to work.

logs:
[factorio-current.log](https://github.com/kirazy/vanilla-loaders-hd/files/5597998/factorio-current.log)
[factorio-previous.log](https://github.com/kirazy/vanilla-loaders-hd/files/5597999/factorio-previous.log)

**Comment by kirazy** [comment]
...I hadn't actually finished the core rework I did in August, but forgot. :D...

All finished and fixed now. You should be good.

Commit 2dbce33216e611eee9cb8bbdc6d62cdaf867fe46 resolves this.
